# Generated by Django 3.1.5 on 2021-01-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('IS', 'In Stock'), ('OS', 'Out of Stock'), ('DC', 'Discontinued')], default='Out of Stock', max_length=12),
        ),
    ]
