# Generated by Django 3.1.5 on 2021-01-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='employee',
            new_name='employee_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='itemQuantity',
        ),
        migrations.AddField(
            model_name='product',
            name='item_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
