# Generated by Django 3.1.5 on 2021-01-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210107_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
